# Generated by Django 6.0.3 on 2026-03-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='pronto',
            new_name='pontos',
        ),
    ]
