# Generated by Django 6.0.3 on 2026-03-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_pronto_cliente_pontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('PRONTA', 'Pronta entrega'), ('ENCOMENDA', 'Encomenda')], default='PRONTA', max_length=20),
        ),
    ]
