# Generated by Django 6.0.3 on 2026-03-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_venda_status_alter_venda_tipo_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_venda',
            new_name='preco_unitario',
        ),
    ]
