# Generated by Django 6.0.3 on 2026-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_preco_venda_produto_preco_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='valor',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartao'), ('TRANSFERENCIA', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
    ]
