# Generated by Django 6.0.3 on 2026-03-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_loteproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
