# Generated by Django 6.0.3 on 2026-03-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_produto_data_validade_remove_produto_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data_limite_retirada',
            new_name='data_limite_pagamento',
        ),
    ]
