# Generated by Django 6.0.3 on 2026-03-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_rename_data_limite_retirada_venda_data_limite_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartao'), ('TRANSFERENCIA', 'Transferencia')], default='DINHEIRO', max_length=20),
        ),
    ]
