# Generated by Django 6.0.3 on 2026-03-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_venda_forma_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='forma_pagamento',
        ),
    ]
