# Generated by Django 6.0.3 on 2026-03-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_remove_pagamento_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('PRONTA-ENTREGA', 'Pronta entrega'), ('ENCOMENDA', 'Encomenda')], default='PRONTA', max_length=20),
        ),
    ]
