# Generated by Django 6.0.3 on 2026-03-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_alter_venda_status_alter_venda_tipo_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('PARCIAL', 'Pago parcialmente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
