# Generated by Django 6.0.3 on 2026-03-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_alter_venda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_devedor',
        ),
    ]
