# Generated by Django 6.0.3 on 2026-03-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_remove_cliente_saldo_devedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('PRONTA_ENTREGA', 'Pronta entrega'), ('ENCOMENDA', 'Encomenda')], default='PRONTA_ENTREGA', max_length=20),
        ),
    ]
