# Generated by Django 6.0.3 on 2026-03-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_alter_venda_tipo_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('ESTOQUE', 'Em Estoque'), ('ENCOMENDA', 'Encomenda')], default='ESTOQUE', max_length=20),
        ),
    ]
