# Generated by Django 6.0.3 on 2026-03-16 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_alter_venda_tipo_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_limite_pagamento',
            field=models.DateField(default=datetime.date(2026, 3, 16), verbose_name='Data limite de pagamento'),
            preserve_default=False,
        ),
    ]
