# Generated by Django 6.0.3 on 2026-03-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_alter_venda_data_limite_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data_encomenda', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PEDIGO', 'Pedido feito'), ('CHEGOU', 'Produto chegou'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue ao cliente')], default='PEDIGO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
