# Generated by Django 6.0.3 on 2026-03-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_encomenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('PEDIDO', 'Pedido feito'), ('CHEGOU', 'Produto chegou'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue ao cliente')], default='PEDIDO', max_length=20),
        ),
    ]
