# Generated by Django 6.0.3 on 2026-03-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_alter_encomenda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('PEDIDO', 'Pedido feito'), ('CHEGOU', 'Produto chegou'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue ao cliente'), ('CANCELADO', 'Cancelado')], default='PEDIDO', max_length=20),
        ),
    ]
