# Generated by Django 6.0.3 on 2026-03-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0020_alter_encomenda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproduto',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
