# Generated by Django 6.0.3 on 2026-03-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0021_alter_loteproduto_data_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='status_pagamento',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando pagamento inicial'), ('PARCIAL', 'Pagamento parcial feito'), ('PAGO', '100% pago')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Pedidp'), ('PEDIDO', 'Pedido feito'), ('CHEGOU', 'Produto chegou'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue ao cliente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
