# Generated by Django 6.0.3 on 2026-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0022_encomenda_status_pagamento_alter_encomenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomenda',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Pedido'), ('PEDIDO', 'Pedido feito'), ('CHEGOU', 'Produto chegou'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue ao cliente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
