# Generated by Django 6.0.3 on 2026-03-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_encomenda_preco_unitario_encomenda_valor_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='preco_unitario',
        ),
    ]
