# Generated by Django 6.0.3 on 2026-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0024_remove_encomenda_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='data_limite_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
