# Generated by Django 6.0.3 on 2026-03-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0025_encomenda_data_limite_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='produto',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='produto',
            field=models.ManyToManyField(related_name='encomenda', to='loja.produto'),
        ),
    ]
