# Generated by Django 6.0.3 on 2026-03-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0026_remove_encomenda_produto_encomenda_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('ESTOQUE', 'Estoque'), ('ENCOMENDA', 'Encomenda')], max_length=15)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status_pagamento', models.CharField(choices=[('AGUARDANDO', 'Aguardando pagamento inicial'), ('PARCIAL', 'Pagamento parcial feito'), ('PAGO', '100% pago'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=15)),
                ('status_item', models.CharField(choices=[('PENDENTE', 'Aguardando Pedido'), ('PEDIDO', 'Pedido feito'), ('CHEGOU', 'Produto chegou'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue ao cliente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência')], max_length=15, null=True)),
                ('data_limite_pagamento', models.DateField(blank=True, null=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.pedido')),
            ],
        ),
        migrations.DeleteModel(
            name='Encomenda',
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
