# Generated by Django 6.0.3 on 2026-03-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0027_remove_itemvenda_produto_remove_itemvenda_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='loja.produto'),
        ),
    ]
