# Generated by Django 6.0.3 on 2026-03-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0028_alter_itempedido_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
