# Generated by Django 6.0.3 on 2026-03-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0029_alter_itempedido_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_limite_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
