# Generated by Django 6.0.3 on 2026-03-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0030_pedido_data_limite_pagamento_pedido_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='data_limite_pagamento',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='status_pagamento',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='valor_pago',
        ),
    ]
