# Generated by Django 6.0.3 on 2026-03-29 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0031_remove_itempedido_data_limite_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='loja.cliente'),
        ),
    ]
