# Generated by Django 6.0.3 on 2026-03-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0032_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='loja.produto'),
        ),
    ]
