# Generated by Django 6.0.3 on 2026-04-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0033_alter_loteproduto_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20),
        ),
    ]
