# Generated by Django 6.0.3 on 2026-04-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0035_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='pontos_creditados',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20),
        ),
    ]
