# Generated by Django 6.0.3 on 2026-04-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0036_itempedido_pontos_creditados_alter_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='pontos_creditados',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pontos_creditados',
            field=models.BooleanField(default=False),
        ),
    ]
