# Generated by Django 6.0.3 on 2026-04-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0037_remove_itempedido_pontos_creditados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cupons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom_usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
