# Generated by Django 6.0.3 on 2026-04-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0040_alter_cliente_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='status_item',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_encomenda',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Pedido'), ('PEDIDO', 'Pedido feito'), ('CHEGOU', 'Produto chegou'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue ao cliente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15),
        ),
    ]
