# Generated by Django 6.0.3 on 2026-04-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0041_remove_itempedido_status_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_pag',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20),
        ),
    ]
