# Generated by Django 6.0.3 on 2026-04-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0042_pedido_status_pag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedidoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='loja.itempedido')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loteproduto')),
            ],
        ),
    ]
