# Generated by Django 6.0.3 on 2026-04-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0043_itempedidolote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_pag',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('EXPIRADO', 'Expirado')], default='ATIVO', max_length=20),
        ),
    ]
