# Generated by Django 6.0.3 on 2026-04-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0044_alter_pedido_status_pag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(error_messages={'unique': 'Já existe um cliente com este telefone'}, max_length=20, unique=True),
        ),
    ]
