# Generated by Django 6.0.3 on 2026-04-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0045_cliente_ativo_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
