# Generated by Django 6.0.3 on 2026-04-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0046_loteproduto_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status_pag',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('EXPIRADO', 'Expirado')], default='ABERTO', max_length=20),
        ),
    ]
