# Generated by Django 6.0.3 on 2026-05-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0047_remove_pedido_status_pag_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_encomenda',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando'), ('PEDIDO', 'Pedido'), ('CHEGOU', 'Chegou'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue ')], default='PENDENTE', max_length=15),
        ),
    ]
